export const ADJECTIVES_PID = 30;

export const ADJECTIVES = [
  { value: "vies mooi", tags: ["HAPPY", "KIND"] },
  { value: "vies", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "vies lelijk", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "vies mottig", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "vies vettig", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "vettige", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "mottige", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "vettig stuk", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "mottig stuk", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "geschifte", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "hoerige", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "slettige", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "aangerande", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "dikke", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "smalle", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "aangetaste", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "aanhankelijke", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "onuitstaanbare", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "niet aantrekkelijke", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "zwellige", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "rattige", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "4-jarige", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "aarslelijke", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "aartsdomme", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "ambetante", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "abnormale", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "abortie", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "absurde", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "moddervette", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "ziekelijke ", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "geblokkeerde", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "triestige", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "afgedankte", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "adoptie", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "aderige", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "affrontelijke ", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "afgezaagde", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "zwette", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "lelijke", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "stuk afval", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "afwijkende", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "zwerende", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "agressieve", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "arige", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "alcoholische", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "addergebroedige", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "anale", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "allerlelijkste", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "allochtone", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "vissige", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "alternatieve", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "analfabetische", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "ananasvormige", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "angolese", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "abnormale", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "nazi", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "bacteriele", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "antwerpse", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "geile", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "armoedige", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "arme", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "arrogante", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "aseksuele", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "asociale", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "asymmetrische", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "monotome", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "autistische", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "baardige", tags: [] },
  { value: "bacteriele", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "bajesmaffe", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "merelbeekse", tags: [] },
  { value: "balense", tags: [] },
  { value: "kapelse", tags: [] },
  { value: "kontichse", tags: [] },
  { value: "jersey ", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "jytte", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "madu", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "mel", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "karense", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "mbali", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "tettige ", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "balkonnige", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "vetlappige", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "basis", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "zieke nul", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "zieke losse ", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "begaaide", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "argan oilige", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "bassige", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "trut", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "kuttige", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "geblokkeerde", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "ziekelijke ", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "zieke", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "zurige", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "zwetende", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "ritsige", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "goeikope", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "bekrompe", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "belachelijke ", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "lastige", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "onbeleefde ", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "bedelende", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "gemiddelde", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "benige", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "zinloze", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "betreurenswaardige", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "betaalde", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "besnorde", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "klere", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "beffige", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "lullige", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "behaarde", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "onbeschofte", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "beteuterde", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "betraande", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "betoeterde", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "onbetrouwbare", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "bevallige", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "bevende", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "bevredigende", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "onbeweegbare", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "bewogen", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "bezopen", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "bezwerende", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "beïnvloedbare", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "nonnige", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "bijdehandse", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "goedgelovige", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "bijzondere", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "biseksuele", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "bittere", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "bitsige", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "blaasvormige", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "blaffe", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "blanke", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "bleke", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "blinde", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "blote", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "bloedende", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "blokkeerbare", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "blubberige", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "blufferige", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "bobbelige ", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "bochelige", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "breekbare", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "bokkige", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "bollende", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "bollige", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "bolronde", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "bommige", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "bonkende", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "boze", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "zure", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "borstige", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "tettige", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "bottige", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "botergeile", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "bovenaardse", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "botswaanse", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "congolese", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "aziatische", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "brakende", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "brallerige", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "brakke", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "brede", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "breekbare", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "brutale", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "brutte", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "buigbare", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "buikige", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "bulgaarse", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "cafeinehoerige", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "niet capabele", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "chagrijnige", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "chaotische", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "chemische", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "chlorische", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "criminele", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "crapuleuze", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "cynische", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "alledaagse", tags: [] },
  { value: "decadente", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "datieve", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "dellige", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "degoutante", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "dempige", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "depressieve", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "derderangse", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "deprimerende", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "diepe", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "destructieve", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "desastreuze", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "diabetische", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "duitse", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "dikke", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "dikmakende", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "dikwandige", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "positieve", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "negatieve", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "jerre", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "doffe", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "mafkees", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "dompige", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "doodarme", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "doodmoe", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "eenvoudige", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "ongelukkige", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "doodzieke", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "doorbloedde", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "doodgerotte", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "rottende", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "rottige", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "natte", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "doorrookte", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "doorrotte", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "doorslechte", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "doosachtige", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "doorzichtige", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "draadachtige", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "drakige", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "drassige", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "drempelverlagende", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "driedeurse", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "driebenige", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "hoekige", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "driejarige", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "drieste", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "driftige", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "drijfnatte", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "dronken", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "dubbele", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "duffe", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "duivelse", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "dunne", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "dwalende", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "dwangmatige", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "dwarse", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "dwergachtige", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "easy", tags: [] },
  { value: "ebonieten", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "echte", tags: [] },
  { value: "eelterige", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "eendaagse", tags: [] },
  { value: "eenjarige", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "oude", tags: [] },
  { value: "eenzame", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "eenvoudige", tags: [] },
  { value: "gierige", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "eigenzinnige", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "eikelige", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "nutteloze", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "nutteloos stuk", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "eivormige", tags: ["ANGRY", "SAD", "GRUMPY"] },
  { value: "elfjarige", tags: [] },
];
