// punct kan na answer komen
// suffix kan na answer komen en voor punct
// prefix kan enkel voor answer komen
// emojis kan na answer komen en voor answer
// answert kan herhaald worden max 1x
// adjectives zijn prefixes en komen voor answer
// emojis kunnen op zichzelf bestaan
// PREFIX kunnen oo op zichzelf bestaan
// Punctuation kunnen op zichzelf bestaan

// als vraagteken in zin -> domme vraag

export const BASIC_ANSWER = [
  { value: "Zeer zeker", tags: ["HAPPY", "KIND", "AGREE"] },
  { value: "Volgens mij wel", tags: ["AGREE"] },
  { value: "Zeer waarschijnlijk wel", tags: ["AGREE"] },
  { value: "Ja", tags: ["AGREE"] },
  { value: "Affirmatief", tags: ["AGREE"] },
  { value: "Correct", tags: ["AGREE"] },
  { value: "Yep", tags: ["AGREE"] },
  { value: "Pak van wel", tags: ["AGREE"] },
  { value: "Zeker en vast", tags: ["HAPPY", "KIND", "AGREE"] },
  { value: "Jazeker", tags: ["AGREE"] },
  { value: "Kan he", tags: ["SAD", "AGREE"] },
  { value: "Natuurlijk", tags: ["HAPPY", "AGREE"] },
  { value: "Mhm", tags: ["NEUTRAL"] },
  { value: "Mh", tags: ["NEUTRAL"] },
  { value: "Ye", tags: ["AGREE"] },
  { value: "Klopt", tags: ["AGREE"] },
  { value: "Is", tags: ["AGREE"] },
  { value: "Zeker", tags: ["AGREE"] },
  { value: "Idd", tags: ["AGREE"] },
  { value: "Ofc", tags: ["AGREE"] },
  { value: "Ja", tags: ["AGREE"] },
  { value: "Tuurlijk", tags: ["HAPPY", "AGREE"] },
  { value: "Wa dacht ge", tags: ["ANGRY", "AGREE"] },
  { value: "Yes", tags: ["AGREE"] },
  { value: "Jaja", tags: ["NEUTRAL"] },
  { value: "Jong", tags: ["NEUTRAL"] },
  { value: "Jom", tags: ["NEUTRAL"] },
  { value: "Dat is een zekerheid", tags: ["HAPPY", "KIND", "AGREE"] },
  { value: "100%", tags: ["AGREE"] },
  { value: "Zal zo zijn", tags: ["AGREE"] },
  { value: "Ja", tags: ["AGREE"] },
  { value: "Sowieso", tags: ["AGREE"] },
  { value: "Zowiezo", tags: ["HAPPY", "KIND", "AGREE"] },
  { value: "Wees daar maar zeker van", tags: ["HAPPY", "KIND", "AGREE"] },
  { value: "Absoluut", tags: ["AGREE"] },
  { value: "Gelijk", tags: ["KIND", "AGREE"] },
  { value: "Zal wel", tags: ["AGREE"] },
  { value: "Is wel", tags: ["AGREE"] },
  { value: "Ja", tags: ["AGREE"] },
  { value: "Altijd gelijk", tags: ["KIND", "AGREE"] },
  { value: "Jaa", tags: ["HAPPY", "KIND", "AGREE"] },
  { value: "Klopt zeker", tags: ["AGREE"] },
  { value: "Yep is zo", tags: ["AGREE"] },
  { value: "Zo is dat", tags: ["AGREE"] },
  { value: "Is zeker zo", tags: ["AGREE"] },
  { value: "Zal wel zijn", tags: ["AGREE"] },
  { value: "Waarschijnlijk", tags: ["AGREE"] },
  { value: "Lijkt mij van wel", tags: ["AGREE"] },
  { value: "Lijkt mij correct", tags: ["AGREE"] },
  { value: "Is zo", tags: ["AGREE"] },
  { value: "Zal kloppen", tags: ["AGREE"] },
  { value: "Tuurlijk", tags: ["KIND", "AGREE"] },
  { value: "Sws", tags: ["AGREE"] },
  { value: "Ja waarom ni", tags: ["AGREE"] },
  { value: "Positief", tags: ["KIND", "AGREE"] },
  { value: "Uiteraard", tags: ["AGREE"] },
  { value: "Vanzelfsprekend", tags: ["AGREE"] },
  { value: "Vast", tags: ["AGREE"] },
  { value: "Natuurlijk", tags: ["HAPPY", "KIND", "AGREE"] },
  { value: "Bevestigd", tags: ["AGREE"] },
  { value: "Uw ja zij ja", tags: ["HAPPY", "KIND", "AGREE"] },
  { value: "Juist", tags: ["HAPPY", "KIND", "AGREE"] },
  { value: "Klopt als een bus", tags: ["KIND", "AGREE"] },
  { value: "Correct", tags: ["KIND", "AGREE"] },
  { value: "Geldig", tags: ["KIND", "AGREE"] },
  { value: "Terecht", tags: ["KIND", "AGREE"] },
  { value: "Waar", tags: ["KIND", "AGREE"] },
  { value: "Jawel", tags: ["KIND", "AGREE"] },
  { value: "Precies", tags: ["AGREE"] },
  { value: "Gewoon", tags: ["NEUTRAL"] },
  { value: "Moet nagaan", tags: ["NEUTRAL"] },
  { value: "Ja nee waarom wel", tags: ["DISAGREE"] },
  { value: "Zeer twijfelachtig", tags: ["DISAGREE"] },
  { value: "Niet hopen", tags: ["DISAGREE"] },
  { value: "Nooit", tags: ["DISAGREE"] },
  { value: "Incorrect", tags: ["DISAGREE"] },
  { value: "Het antwoord is nee", tags: ["DISAGREE"] },
  { value: "Nope", tags: ["DISAGREE"] },
  { value: "Nee", tags: ["DISAGREE"] },
  { value: "Nooit van z'n leven", tags: ["DISAGREE", "ANGRY"] },
  { value: "Van z'n leven ni", tags: ["DISAGREE", "ANGRY"] },
  { value: "Nop", tags: ["DISAGREE", , "ANGRY"] },
  { value: "Nah", tags: ["DISAGREE", , "ANGRY"] },
  { value: "Neh", tags: ["DISAGREE", , "ANGRY"] },
  { value: "Denk ni", tags: ["DISAGREE"] },
  { value: "Is ni", tags: ["DISAGREE"] },
  { value: "Fout", tags: ["DISAGREE"] },
  { value: "Neje", tags: ["DISAGREE"] },
  { value: "Neen", tags: ["DISAGREE"] },
  { value: "Tuurlijk ni", tags: ["DISAGREE", "ANGRY"] },
  { value: "Nee", tags: ["DISAGREE"] },
  { value: "Nooope", tags: ["DISAGREE", "ANGRY"] },
  { value: "Zal wel ni", tags: ["DISAGREE"] },
  { value: "Nee", tags: ["DISAGREE"] },
  { value: "Is niet", tags: ["DISAGREE"] },
  { value: "Sws niet", tags: ["DISAGREE"] },
  { value: "Kan nooit", tags: ["DISAGREE", "ANGRY"] },
  { value: "Nee", tags: ["DISAGREE"] },
  { value: "Nop", tags: ["DISAGREE"] },
  { value: "Kan niet", tags: ["DISAGREE"] },
  { value: "0% kans", tags: ["DISAGREE"] },
  { value: "Sowieso niet", tags: ["DISAGREE"] },
  { value: "Zowiezo niet", tags: ["DISAGREE"] },
  { value: ":x:", tags: ["DISAGREE"] },
  { value: "Ik ben daar niet zeker van", tags: ["DISAGREE"] },
  { value: "Met zekerheid niet", tags: ["DISAGREE"] },
  { value: "Gewoon nee", tags: ["DISAGREE", "ANGRY"] },
  { value: "Nee jom", tags: ["DISAGREE", "ANGRY"] },
  { value: "Nee jong", tags: ["DISAGREE", "ANGRY"] },
  { value: "Tzal", tags: ["DISAGREE", "ANGRY"] },
  { value: "Denkt gij", tags: ["DISAGREE"] },
  { value: "Is ni", tags: ["DISAGREE"] },
  { value: "Maja nee", tags: ["DISAGREE", "ANGRY"] },
  { value: "Zeker niet", tags: ["DISAGREE"] },
  { value: "Een kat is geen mus", tags: ["DISAGREE", "ANGRY"] },
  { value: "Zwijg nu eens", tags: ["DISAGREE", "ANGRY"] },
  { value: "Nee zwijg", tags: ["DISAGREE", "ANGRY"] },
  { value: "Geef het op aub", tags: ["DISAGREE", "ANGRY"] },
  { value: "Negatief", tags: ["DISAGREE", "ANGRY"] },
  { value: "Helaas", tags: ["DISAGREE"] },
  { value: "Da weet ik nie", tags: ["CONFUSED", "ANGRY"] },
  { value: "Och $SCHELD me al die vragen", tags: ["CONFUSED", "ANGRY"] },
  { value: "Kheb er geen idee van", tags: ["CONFUSED", "ANGRY"] },
  { value: "Ik hoop dat ge erin stikt", tags: ["ANGRY"] },
  { value: "Hou uw kutbek $SCHELD", tags: ["ANGRY"] },
  { value: "Vermoeiend", tags: ["ANGRY"] },
  { value: "Ik wil dood", tags: ["SAD", "ANGRY"] },
  { value: "Zou beter zwijgen", tags: ["ANGRY"] },
  { value: "Weet ik ni", tags: ["CONFUSED", "ANGRY"] },
  { value: "Domme vraag", tags: ["ANGRY"] },
  { value: "Ga ni op antwoorden", tags: ["CONFUSED", "ANGRY"] },
  { value: "Wa", tags: ["CONFUSED"] },
  { value: "ff werken dan antwoord ik", tags: ["BUSY"] },
  { value: "secondje, stuur u straks", tags: ["BUSY"] },
  { value: "stuur u straks", tags: ["BUSY"] },
  { value: "w8 ff", tags: ["BUSY"] },
  { value: "wacht ff", tags: ["BUSY"] },
  { value: "nu ff niet", tags: ["BUSY"] },
  { value: "even geduld", tags: ["BUSY"] },
  { value: "de jap de jap de jap", tags: ["ANGRY"] },
  { value: "moet ni zoveel vragen stellen", tags: ["ANGRY"] },
  { value: "nutteloze vraag", tags: ["ANGRY"] },
  { value: "zwijg", tags: ["ANGRY"] },
  { value: "zwijgt nu toch eens", tags: ["ANGRY"] },
  { value: "ma laat mij nu eens doen", tags: ["BUSY", "ANGRY"] },
  { value: "idk", tags: ["CONFUSED"] },
  { value: "geen idee", tags: ["CONFUSED"] },
  { value: "waarom zou ik da weten", tags: ["CONFUSED"] },
  { value: "moet ik da weten", tags: ["CONFUSED"] },
  { value: "kan ik ni weten", tags: ["CONFUSED", "ANGRY"] },
  { value: "vraagt iemand anders eens", tags: ["BUSY", "ANGRY"] },
  { value: "val eens iemand anders lastig", tags: ["CONFUSED", "ANGRY"] },
  { value: "laat me doen", tags: ["BUSY", "ANGRY"] },
  { value: "vraag straks ff bezig", tags: ["BUSY"] },
  { value: "ff weg", tags: ["BUSY"] },
  { value: "Ben er nu niet", tags: ["BUSY"] },
  { value: "Kan nu niet antwoorden", tags: ["BUSY"] },
  { value: "Ff geen tijd", tags: ["BUSY"] },
  { value: "Zal straks antwoorden", tags: ["BUSY"] },
  { value: "Kom hier dadelijk op terug", tags: ["BUSY"] },
  { value: "Bel zo terug", tags: ["BUSY"] },
  { value: "Ff kaf halen", tags: ["BUSY"] },
  { value: "Jat kaf ff", tags: ["BUSY"] },
  { value: "Jatje kaf halen", tags: ["BUSY"] },
];
