export const SENTENCES_ADVANCED = [
  { value: "Kaf minder vandaag", tags: [] },
  { value: "Weer van dieje rommel kaf", tags: [] },
  { value: "Kga passen voor poep", tags: [] },
  { value: "Denk wel poepke om $TIME", tags: [] },
  { value: "Mooi weer vandaag precies", tags: [] },
  { value: "Mooi weer vandaag", tags: [] },
  { value: "Minder weer vandaag", tags: [] },
  { value: "Tis wa bewolk", tags: [] },
  { value: "Tzonneke schijnt se", tags: [] },
  { value: "Blauwe hemel", tags: [] },
  { value: "Geen wolkske aan de lucht", tags: [] },
  { value: "Prachtige dag", tags: [] },
  { value: "Zal maar eens beginnen zeker", tags: [] },
  { value: "Denk tijd om te stoppen", tags: [] },
  { value: "Goed geweest voor vandaag", tags: [] },
  { value: "Ik stop ermee", tags: [] },
  { value: "Ik wil dood", tags: ["SAD"] },
  { value: "Ik kan er niks van", tags: [] },
  { value: "Ik begrijp hier niks van", tags: [] },
  { value: "Ik wil ff weg", tags: ["SAD"] },
  { value: "Ik wil verlof", tags: ["SAD"] },
  { value: "Wanneer zijn we weg", tags: [] },
  { value: "Tijd om te gaan", tags: [] },
  { value: "Kga blij zijn als gelle weg bent", tags: ["ANGRY"] },
  { value: "Kmoet u ni $WHO", tags: ["ANGRY"] },
  { value: "Wa doet gij hier nog $WHO", tags: ["ANGRY"] },
  { value: "Slaat nergens op $WHO", tags: ["ANGRY"] },
  { value: "Wat nen onzin $WHO", tags: ["ANGRY"] },
  { value: "Klopt $WHO", tags: [] },
  { value: "Iets te zeggen $WHO", tags: [] },
  { value: "Had gij iets gezegd $WHO", tags: [] },
  { value: "Kunt gellie eigenlijk iets", tags: [] },
  { value: "Welle weg ofw", tags: [] },
  { value: "Naar waar ist", tags: [] },
  { value: "Gaan we naar $PLACE", tags: [] },
  { value: "Ff naar $PLACE", tags: [] },
  { value: "Strak naar $PLACE ofw", tags: [] },
  { value: "Volgende week $PLACE", tags: [] },
  { value: "Wa bent gij hier nog $WHO", tags: [] },
  { value: "Volgende week $WHO", tags: [] },
  { value: "Ga gij nog neuken $WHO", tags: [] },
  { value: "Volgende week $PLACE $VERB met $WHO", tags: [] },
  { value: "Ff $VERB met $WHO", tags: [] },
  { value: "Ff $VERB met $WHAT", tags: [] },
  { value: "Ff $VERB", tags: [] },
  { value: "Ff $WHAT $VERB", tags: [] },
];

export const SENTENCES_BASIC = [
  { value: "Allee tot ziens nu" },
  { value: "De groeten" },
  { value: "Maggie out :v: " },
  { value: "Over en out" },
  { value: "Ff weg nu" },
  { value: "Ff moe nu, dutje" },
  { value: "ff kaf" },
  { value: "Hoogachtend, Maggie" },
  { value: "Tot de volgende" },
  { value: "Doeg" },
  { value: "Houdoe" },
  { value: "Nu ben ik wel echt weg" },
  { value: "Want de bel doet het niet" },
  { value: "En laat me nu doen" },
  { value: "En zwijg nu" },
  { value: "En als ge mij nog 1 keer tagt krijgt ge lappen" },
  { value: "En gy bent een %ADJECTIVE %SCHELD" },
  { value: "En dans" },
  { value: "Zucht" },
  { value: "Dag" },
  { value: "Laat me doen %SCHELD" },
  { value: "%SHELD" },
  { value: "Blij u van dienst te kunnen zijn" },
];
