export const SENTENCES_ADVANCED = [
  { value: "Kaf minder vandaag", tags: [] },
  { value: "Weer van dieje rommel kaf", tags: [] },
  { value: "Kga passen voor poep", tags: [] },
  { value: "Denk wel poepke om %TIME", tags: [] },
  { value: "Mooi weer vandaag precies", tags: [] },
  { value: "Mooi weer vandaag", tags: [] },
  { value: "Minder weer vandaag", tags: [] },
  { value: "Tis wa bewolk", tags: [] },
  { value: "Tzonneke schijnt se", tags: [] },
  { value: "Blauwe hemel", tags: [] },
  { value: "Geen wolkske aan de lucht", tags: [] },
  { value: "Prachtige dag", tags: [] },
  { value: "Zal maar eens beginnen zeker", tags: [] },
  { value: "Denk tijd om te stoppen", tags: [] },
  { value: "Goed geweest voor vandaag", tags: [] },
  { value: "Ik stop ermee", tags: [] },
  { value: "Ik wil dood", tags: ["SAD"] },
  { value: "Ik kan er niks van", tags: [] },
  { value: "Ik begrijp hier niks van", tags: [] },
  { value: "Ik wil ff weg", tags: ["SAD"] },
  { value: "Ik wil verlof", tags: ["SAD"] },
  { value: "Wanneer zijn we weg", tags: [] },
  { value: "Tijd om te gaan", tags: [] },
  { value: "Kga blij zijn als gelle weg bent", tags: ["ANGRY"] },
  { value: "Kmoet u ni %WHO", tags: ["ANGRY"] },
  { value: "Wa doet gij hier nog %WHO", tags: ["ANGRY"] },
  { value: "Slaat nergens op %WHO", tags: ["ANGRY"] },
  { value: "Wat nen onzin %WHO", tags: ["ANGRY"] },
  { value: "Klopt %WHO", tags: [] },
  { value: "Iets te zeggen %WHO", tags: [] },
  { value: "Had gij iets gezegd %WHO", tags: [] },
  { value: "Kunt gellie eigenlijk iets", tags: [] },
  { value: "Welle weg ofw", tags: [] },
  { value: "Naar waar ist", tags: [] },
  { value: "Gaan we naar %PLACE", tags: [] },
  { value: "Ff naar %PLACE", tags: [] },
  { value: "Strak naar %PLACE ofw", tags: [] },
  { value: "Volgende week %PLACE", tags: [] },
  { value: "Wa bent gij hier nog %WHO", tags: [] },
  { value: "Volgende week %WHO", tags: [] },
  { value: "Ga gij nog neuken %WHO", tags: [] },
  { value: "Volgende week %PLACE %VERB met %WHO", tags: [] },
  { value: "Ff %VERB met %WHO", tags: [] },
  { value: "Ff %VERB met %WHAT", tags: [] },
  { value: "Ff %VERB", tags: [] },
  { value: "Ff %WHAT %VERB", tags: [] },
  { value: "%WHO %VERB ofw", tags: [] },
  { value: "%WHO %WHAT?", tags: [] },
  { value: "Denk ni da %WHO %WHAT?", tags: [] },
  { value: "Denk ni da %WHAT altijd %WHAT?", tags: [] },
  { value: "%WHO %PLACE wist ni", tags: [] },
  { value: "Zijde gij hier nog, %WHO", tags: [] },
  { value: "Mag ik u ff storen, %WHO", tags: [] },
  { value: "Seg kzou %WHAT, wat denkt ge?", tags: [] },
  { value: "Seg kzou ff willen spreken met %WHO over %WHAT", tags: [] },
  { value: "Onlangs %WHO gehoord", tags: [] },
  { value: "Jaja %ADJECTIVE %WHAT altijd zelfde", tags: [] },
  { value: "Al %WHAT @%WHO ?", tags: [] },
  { value: "Kunt gij da? %WHO", tags: [] },
];

export const SENTENCES_BASIC = [
  { value: "Allee tot ziens" },
  { value: "De groeten" },
  { value: "Doe %WHO de groetjes" },
  { value: "Ff weg nu" },
  { value: "Ff moe nu" },
  { value: "Ff dutje" },
  { value: "Ff %WHAT" },
  { value: "Ja jong ja" },
  { value: "Ff %PLACE" },
  { value: "Ff kaf" },
  { value: "Nu weg, tot de volgende" },
  { value: "Ff weg, Houdoe" },
  { value: "Ja nu wel echt weg" },
  { value: "Nu ben ik wel echt weg" },
  { value: "Want de bel doet het niet" },
  { value: "En laat me nu doen" },
  { value: "zwijg maar" },
  { value: "zwijg maar %WHO" },
  { value: "En als ge mij nog 1 keer tagt krijgt ge lappen" },
  { value: "Subiet lappen, jaja gij %WHO" },
  { value: "En gy bent een %ADJECTIVE %SCHELD" },
  { value: "En ff %ADJECTIVE %SCHELD" },
  { value: "En dans" },
  { value: "Zucht" },
  { value: "Dag" },
  { value: "Laat me doen %SCHELD" },
  { value: "%SCHELD" },
  { value: "En nu ff ni %WHO" },
  { value: "Ff %WHAT. Tot subiet" },
  { value: "Ff %WHO. Tot subiet" },
  { value: "Lang niet meer gehoord, %WHO ?" },
  { value: "Waarom %WHO?" },
  { value: "Ff weg %WHO?" },
  { value: "Doeg %WHO?" },
  { value: "En tijd voor kaf %WHO?" },
  { value: "En subiet poepke %WHO?" },
  { value: "Ah is lang geleden %WHO?" },
];
