export const BASIC_ANSWER = [
    "Ik denk van wel?",
    "Zonder twijfel",
    "Zeer zeker",
    "Da weet ik nie",
    "Volgens mij wel",
    "Zeer waarschijnlijk wel",
    "Nee lol",
    "Kans lijkt mij groot",
    "Ja",
    "Kans lijkt mij klein",
    "Zeer twijfelachtig",
    // ":ye: :boi:",
    "Niet hopen.",
    "Ik ben even weg. Jat kaffe halen",
    "Nooit.",
    "Incorrect.",
    "Affirmatief.",
    "Correct.",
    "Laat mij eens me rust vieze slet me al die vragen",
    "Ik heb het opgezocht en het antwoord is nee",
    "Mijn database zegt ja",
    "Nope.",
    "Yep.",
    "Excuseer? Pak van wel",
    "Kheb er geen idee van maar het zal wel",
    "Zeker en vast",
   // "Ik hoop dat ge erin stikt",
   // "Ge bent een vieze slet dus nee",
    // "Hou uw kutbek slonzige slet",
   // "Jij wel xxx",
   // "Sterf.",
    "Ja, slet",
    "Kan he",
    "Pffffff vermoeiend",
   // "Ik wil dood.",
   // "Ja joepie"
  ];