export const GAME_ANSWERS = [
  "poep",
  "solo",
  "vogel",
  "poeptjen",
  "pest",
  "lucky numberken",
  "higher lower",
  "hoger lager",
  "schaar steen papier",
  "blad steen schaar",
  "rps",
  "poeps",
  "kiest iets jong",
  "koekop",
  "6nimmt",
  "perudo",
  "dudoke",
  "dobbelken",
];
