export const BASIC_SUFFIX = [
    "Zucht.",
    "Allee tot ziens nu he.",
    "De groeten.",
    "Maggie out :v: ",
    "Over en out",
    "Ff weg nu",
    "Slet.",
    "Hoer.",
    "En laat me nu doen",
    "Ff moe nu, dutje",
    "ff kaf",
    "En zwijg nu?",
    "En als ge mij nog 1 keer tagt krijgt ge lappen.",
    "Tot ziens xoxo",
    "Daag.",
    "Hoogachtend, Maggie.",
    "Blij u van dienst te kunnen zijn",
    "Tot de volgende.",
    "Doeg",
    "Houdoe",
    "Nu ben ik wel echt weg",
    "En gy bent een %adjective% %scheld% overigens.",
    "En dans",
    "Want de bel doet het niet."
];