export const BASIC_DISAGREE_ANSWER = [
    "Zeer twijfelachtig.",
    "Niet hopen.",
    "Nooit.",
    "Incorrect.",
    "Ik heb het opgezocht en het antwoord is nee.",
    "Nope.",
    "Ge bent een vieze slet dus nee.",
    "Nee.",
    "Nooit van z'n leven.",
    "Nee",
    "Nop",
    "Nah",
    "Neh",
    "Denk ni",
    "Is ni",
    "Fout",
    "Neje",
    "Neen",
    "Tuurlijk ni?",
    "Nee?",
    "Tf nee",
    "Nee...",
    "Nooope",
    "Nee wtf",
    "Zal wel ni",
    "Kans is klein",
    "Tf zegt ge, nee",
    "Nee, domme vraag",
    "Is niet",
    "Sws niet",
    "Kan nooit"
  ];