export const BASIC_AGREE_ANSWER = [
    "Zeer zeker.",
    "Volgens mij wel.",
    "Zeer waarschijnlijk wel.",
    "Ja.",
    ":ye: :boi:",
    "Affirmatief.",
    "Correct.",
    "Yep.",
    "Pak van wel.",
    "Zeker en vast.",
    "Jazeker slet.",
    "Kan he.",
    "Natuurlijk!",
    "Mhm",
    "Mh",
    "Ye",
    "Klopt",
    "Is",
    "Zeker",
    "Idd",
    "Ofc",
    "Ja?",
    "Tuurlijk?",
    "Is?",
    "Ja, wa dacht ge?",
];