export const BASIC_AGREE_ANSWER = [
    "Zeer zeker.",
    "Volgens mij wel.",
    "Zeer waarschijnlijk wel.",
    "Ja.",
    ":ye: :boi:",
    "Affirmatief.",
    "Correct.",
    "Yep.",
    "Pak van wel.",
    "Zeker en vast.",
    "Jazeker slet.",
    "Kan he.",
    "Natuurlijk!",
    "Mhm",
    "Mh",
    "Ye",
    "Klopt",
    "Is",
    "Zeker",
    "Idd",
    "Ofc",
    "Ja?",
    "Tuurlijk?",
    "Is?",
    "Ja, wa dacht ge?",
    "Yes",
    "Ja xD",
    "Yep xD",
    "Ja.....",
    "Jaja..",
    "Ja jong",
    "Ja jom",
    "Dat is een zekerheid.",
    "100%",
    "Zal zo zijn",
    "Ja xx",
    "Sowieso",
    "Zowiezo",
    "Wees daar maar zeker van",
    "Absoluut",
    "Ja ge hebt gelijk..",
    "Zal wel",
    "Denk wel",
    "Is wel",
    ":white_check_mark:",
    "Ja hoor",
    "Ja jij hebt altijd gelijk xoxo.",
    "Jaa"
];