export const BASIC_AGREE_ANSWER = [
    "Zonder twijfel",
    "Zeer zeker",
    "Volgens mij wel",
    "Zeer waarschijnlijk wel",
    "Kans lijkt mij groot",
    "Ja",
    ":ye: :boi:",
    "Affirmatief.",
    "Correct.",
    "Mijn database zegt ja",
    "Yep.",
    "Pak van wel",
    "Denk het",
    "Zeker en vast",
    "Jazeker slet",
    "Kan he",
    "Joepie!",
    "Natuurlijk!"
];