export const BASIC_SUFFIX = [
    "Zucht.",
    ":simple_smile:",
    ":joy:",
    "Allee tot ziens nu he.",
    "De groeten.",
    ":eggplant:",
    "Maggie out :v: ",
    "Over en out",
    "Ik moet nu trouwens even weg, tot ziens!",
    "Slet.",
    "Hoer",
    "Laat mij nu eens me rust.",
    "Ik ben nu even moe, ik ga een dutje doen",
    ":simpeler:",
    ":v:",
    ":hoh:",
    ":yum:",
    ":sunglasses:",
    "lit fam yolo sweg yuuuuuuuw"
];