export const BASIC_DONT_KNOW_ANSWER = [
    "Da weet ik nie.",
    "Ik ben even weg. Jat kaffe halen.",
    "Och vieze slet me al die vragen.",
    "Kheb er geen idee van maar het zal wel.",
    "Ik hoop dat ge erin stikt.",
    "Hou uw kutbek slonzige slet.",
    "Sterf.",
    "Pffffff vermoeiend.",
    "Ik wil dood.",
    "Joepie!",
    "Zou beter zwijgen",
    "Weet ik ni",
    "Domme vraag",
    "Ga ni op antwoorden",
    "Wa?",
    "lol",
    "KEKW",
    "ff kaf",
    "vraag straks ff bezig",
    "ff werken dan antwoord ik",
    "secondje, stuur u straks xxx",
    "w8 ff",
    "meh",
    "nu ff niet",
    "even geduld"
  ];