export const BASIC_PHRASE = [
    "Haha.",
    "Lol.",
    "Ik wil hier liever niet op antwoorden maar...",
    "Even denken...",
    "Ah hm...",
    "Euh...",
    "Mhm...",
    "XD",
    "Hoh.",
    ":')",
    "Lachwekkend.",
    "Triest.",
    "Zielige steen.",
    "k",
    "Ok.",
    "Wat een vraag?",
    "Pfff..",
    "Vermoeiend?",
    "Gy bent dom?",
    "Kunt gij eigenlijk iets?",
    "Zou beter opkankeren. En..",
    "Tyfushoer.",
    "Kalm he",
    "Blij dat je mij stuurt xxx.",
    "Halloooooooo.",
    "Hey hoi.",
    "Aanwezig.",
    "Eigenlijk boeit het mij niet."
  ];